# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Run benchmark # files are saved here .benchmarks/Linux-CPython-3.9-64bit/
        run: |
          pip install -q -r requirements.txt
          pytest bench.py --benchmark-autosave
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .benchmarks/Linux-CPython-3.9-64bit/
          
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
        
      - uses: actions/checkout@v2
        with:
          ref: benchmark
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Mkdir
        run: |
          mkdir benchmark_tests
          cd benchmark_tests
        
      - name: Store data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin benchmark --allow-unrelated-histories
          git add '*.json'
          git commit -m "benchmark results"
          git push origin HEAD:benchmark



#       - uses: actions/upload-artifact@v2
#         with:
#           name: my-artifact
#           path:
#       - name: Store benchmark result
#         uses: rhysd/github-action-benchmark@v1
#         with:
#           name: Python Benchmark with pytest-benchmark
#           tool: 'pytest'
#           output-file-path: output.json
#           # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
#           github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
#           auto-push: true
#           # Show alert with commit comment on detecting possible performance regression
#           alert-threshold: '200%'
#           comment-on-alert: true
#           fail-on-alert: true
#           alert-comment-cc-users: '@CherylTo'
#       - name: View results
#         run: echo "You can view results here https://cherylto.github.io/benchmark-test/dev/bench/"
